name: build

on:
  push:
    branches:
      - dev

env:
  apiKey: ${{ secrets.GCP_API_KEY }}
  projectId: ${{ secrets.GCP_PROJECT_ID }}
  storageBucket: ${{ secrets.GCP_STORAGE_BUCKET }}
  serviceAccount: ${{ secrets.gcp_credentials }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python version
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Create and start virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate

      - name: Make directory repo
        run: |
          mkdir repo

      - name: Make temp directory for phonebook
        run: |
          mkdir temp

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.gcp_credentials }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
      
      - name: Run tests for disk file storage with pytest
        run: |
          pytest -s -vv tests/test_storage.py --service "local"

      - name: Run tests for inmemory db
        run: |
          pytest -s -vv tests/test_databases.py --db "inmemory"

      - name: Run tests for Filesystem db
        run: |
          pytest -s -vv tests/test_databases.py --db "filesystem"
