name: build

on:
  pull_request:
    types: closed
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python version
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Create and start virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Make directory repo
        run: |
          mkdir repo
      
      - id: auth
        uses: google-github-actions/auth@v0
        with:
          service_account: ${{ secrets.gcp_credentials }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0

      - name: Test with pytest
        run: |
          pytest -s -vv tests/test_storage.py --service "cloud"
